# Configuration générale
replicaCount: 1

# Image Docker
image:
  repository: ghcr.io/darkkem/t-clo-902/back
  tag: latest

service:
  name: back-service
  type: ClusterIP
  protocol: TCP
  port: 80

docker:
  port: 80

env:
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql-headless"
  DB_PORT: "3306"
  DB_DATABASE: "res"
  DB_USERNAME: "admin"
  DB_PASSWORD: "admin"

  RABBITMQ_HOST: ""
  RABBITMQ_PORT: ""
  RABBITMQ_USER: ""
  RABBITMQ_PASSWORD: ""
  RABBITMQ_VHOST: ""

  ELASTICSEARCH_HOST: "elasticsearch-master-headless"
  ELASTICSEARCH_PORT: "9200"
  ELASTICSEARCH_SCHEME: "http"