apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front
  annotations:
    # Ajoutez ici les annotations spécifiques à votre configuration
spec:
  rules:
  - host: testfront.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-service
            port:
              number: 4200
