# Configuration générale
replicaCount: 1

# Image Docker
image:
  repository: ghcr.io/darkkem/t-clo-902/front
  tag: latest

# Service
service:
  name: front-service
  type: ClusterIP
  protocol: TCP
  port: 80

docker:
  port: 80

ingress:
  host: testfront.com
  frontService: front-service
  frontPort: 80
  backService: back-service
  backPort: 80
