# Configuration générale
replicaCount: 1

# Image Docker
image:
  repository: ghcr.io/darkkem/t-clo-902/front
  tag: latest

# Service
service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
