# Configuration générale
replicaCount: 1

# Image Docker
image:
  repository: ghcr.io/darkkem/t-clo-902/reporting
  tag: latest

service:
  name: reporting-service
  type: ClusterIP
  protocol: TCP
  port: 80

docker:
  port: 8080

env:
  WEBHOOK_URL: "https://epitechfr.webhook.office.com/webhookb2/b24e61d1-bee9-4b79-b9e8-edd4780e0286@901cb4ca-b862-4029-9306-e5cd0f6d9f86/IncomingWebhook/8d62799eb4b948f4ac01364a26aa35cd/36a66656-9673-456d-8f2b-772dc8a881b4"
  DB_URI: "admin:admin@tcp(mysql:3306)/res"
